from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class LawCategory(str, Enum):
    UNIVERSAL = "Universal"
    DOMAIN = "Domain"
    TENANT = "Tenant"


class LawSeverity(str, Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    CRITICAL = "Critical"


class Law(BaseModel):
    id: str = Field(..., min_length=1, description="Unique identifier for the law (e.g., 'GCP.1')")
    category: LawCategory = Field(..., description="Category of the law")
    text: str = Field(..., min_length=1, description="The actual text of the law/principle")
    severity: LawSeverity = Field(default=LawSeverity.MEDIUM, description="Severity of violation")
    tags: List[str] = Field(default_factory=list, description="Tags for classification")
    source: Optional[str] = Field(default=None, description="Source reference (e.g., 'FDA 21 CFR')")


class Constitution(BaseModel):
    version: str = Field(..., description="Version of this constitution set")
    laws: List[Law] = Field(default_factory=list, description="List of laws")


class Critique(BaseModel):
    violation: bool = Field(..., description="True if a constitutional violation was detected")
    article_id: Optional[str] = Field(default=None, description="The ID of the violated law (e.g., 'GCP.4')")
    severity: LawSeverity = Field(default=LawSeverity.LOW, description="Severity of the detected violation")
    reasoning: str = Field(..., description="Explanation of why the content is or is not compliant")


class ConstitutionalTrace(BaseModel):
    input_draft: str = Field(..., description="The original content generated by the agent")
    critique: Critique = Field(..., description="The critique object generated by the Judge")
    revised_output: str = Field(..., description="The final content after revision (or original if valid)")
    delta: Optional[str] = Field(default=None, description="Unified diff showing changes made for safety")
